selectors:
  taobao:
    domain: ["taobao.com", "tmall.com"]
    title: "#tbpc-detail-item-title > h1"
    price:
      className: ".text--Mdqy24Ex"
      pattern: "^[¥$€£]?\\s*\\d+\\.?\\d*.*"
    image: "div.innerWrap--tD6LdQYX > div > img"

  jd:
    domain: ["jd.com"]
    title: ".sku-name"
    price:
      className: ".p-price .price"
      pattern: "^[¥$€£]?\\s*\\d+\\.?\\d*.*"
    image: "#spec-img"

  amazon:
    domain: ["amazon.com"]
    title: "#productTitle"
    price:
      className: ".a-offscreen"
      pattern: "\\d+([,.]\\d{1,2})?"
    image: "#landingImage"

  ebay:
    domain: ["ebay.com"]
    title: ".x-item-title h1"
    price:
      className: ".x-price-primary"
      pattern: "^[¥$€£]?\\s*\\d+\\.?\\d*.*"
    image: ".ux-image-carousel-item.active img"

  temu:
    domain: ["temu.com"]
    title: ".goods-title"
    price:
      className: ".cur-price"
      pattern: "^[¥$€£]?\\s*\\d+\\.?\\d*.*"
    image: ".goods-image img"